version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: taller_mecanico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/taller-mecanico
    container_name: taller-backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/taller_mecanico
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/taller-grupo13
    container_name: taller-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data: