spring.application.name=taller-mecanico

# conexion a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/taller_mecanico
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# configuracion para jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

