-- =========================
-- BASE DE DATOS
-- =========================
CREATE DATABASE taller_mecanico;

-- =========================
-- TABLAS
-- =========================

CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    telefono VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE vehiculos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR(255),
    modelo VARCHAR(255),
    placa VARCHAR(255),
    cliente_id BIGINT
);

CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    descripcion VARCHAR(255),
    precio DOUBLE PRECISION,
    stock INTEGER
);

CREATE TABLE servicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(255),
    estado VARCHAR(255),
    fecha DATE,
    vehiculo_id BIGINT,
    CONSTRAINT servicios_estado_check CHECK (
        estado IN ('PENDIENTE','EN_PROCESO','TERMINADO','CANCELADO')
    )
);

CREATE TABLE facturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE,
    total DOUBLE PRECISION,
    cliente_id BIGINT
);

CREATE TABLE detalle_factura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad INTEGER,
    precio_unitario DOUBLE PRECISION,
    subtotal DOUBLE PRECISION,
    factura_id BIGINT,
    producto_id BIGINT
);

CREATE TABLE servicio_producto (
    servicio_id BIGINT,
    producto_id BIGINT
);

-- =========================
-- RELACIONES (FOREIGN KEYS)
-- =========================

ALTER TABLE vehiculos
ADD CONSTRAINT fk_vehiculo_cliente
FOREIGN KEY (cliente_id) REFERENCES clientes(id);

ALTER TABLE servicios
ADD CONSTRAINT fk_servicio_vehiculo
FOREIGN KEY (vehiculo_id) REFERENCES vehiculos(id);

ALTER TABLE facturas
ADD CONSTRAINT fk_factura_cliente
FOREIGN KEY (cliente_id) REFERENCES clientes(id);

ALTER TABLE detalle_factura
ADD CONSTRAINT fk_detalle_factura
FOREIGN KEY (factura_id) REFERENCES facturas(id);

ALTER TABLE detalle_factura
ADD CONSTRAINT fk_detalle_producto
FOREIGN KEY (producto_id) REFERENCES productos(id);

ALTER TABLE servicio_producto
ADD CONSTRAINT fk_sp_servicio
FOREIGN KEY (servicio_id) REFERENCES servicios(id);

ALTER TABLE servicio_producto
ADD CONSTRAINT fk_sp_producto
FOREIGN KEY (producto_id) REFERENCES productos(id);